/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployerIndexRouteImport } from './routes/employer.index'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as DashboardResumeRouteImport } from './routes/dashboard_.resume'
import { Route as DashboardApplicationsRouteImport } from './routes/dashboard_.applications'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DashboardAtsIndexRouteImport } from './routes/dashboard_.ats.index'
import { Route as EmployerJobsNewRouteImport } from './routes/employer.jobs.new'
import { Route as DashboardAtsIdRouteImport } from './routes/dashboard_.ats.$id'
import { Route as EmployerJobsIdEditRouteImport } from './routes/employer.jobs.$id.edit'
import { Route as EmployerJobsIdApplicantsRouteImport } from './routes/employer.jobs.$id.applicants'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerIndexRoute = EmployerIndexRouteImport.update({
  id: '/employer/',
  path: '/employer/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JobsRoute,
} as any)
const DashboardResumeRoute = DashboardResumeRouteImport.update({
  id: '/dashboard_/resume',
  path: '/dashboard/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardApplicationsRoute = DashboardApplicationsRouteImport.update({
  id: '/dashboard_/applications',
  path: '/dashboard/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardAtsIndexRoute = DashboardAtsIndexRouteImport.update({
  id: '/dashboard_/ats/',
  path: '/dashboard/ats/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerJobsNewRoute = EmployerJobsNewRouteImport.update({
  id: '/employer/jobs/new',
  path: '/employer/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAtsIdRoute = DashboardAtsIdRouteImport.update({
  id: '/dashboard_/ats/$id',
  path: '/dashboard/ats/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerJobsIdEditRoute = EmployerJobsIdEditRouteImport.update({
  id: '/employer/jobs/$id/edit',
  path: '/employer/jobs/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerJobsIdApplicantsRoute =
  EmployerJobsIdApplicantsRouteImport.update({
    id: '/employer/jobs/$id/applicants',
    path: '/employer/jobs/$id/applicants',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/jobs/$id': typeof JobsIdRoute
  '/employer/': typeof EmployerIndexRoute
  '/dashboard/ats/$id': typeof DashboardAtsIdRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/dashboard/ats/': typeof DashboardAtsIndexRoute
  '/employer/jobs/$id/applicants': typeof EmployerJobsIdApplicantsRoute
  '/employer/jobs/$id/edit': typeof EmployerJobsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/jobs/$id': typeof JobsIdRoute
  '/employer': typeof EmployerIndexRoute
  '/dashboard/ats/$id': typeof DashboardAtsIdRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/dashboard/ats': typeof DashboardAtsIndexRoute
  '/employer/jobs/$id/applicants': typeof EmployerJobsIdApplicantsRoute
  '/employer/jobs/$id/edit': typeof EmployerJobsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard_/applications': typeof DashboardApplicationsRoute
  '/dashboard_/resume': typeof DashboardResumeRoute
  '/jobs/$id': typeof JobsIdRoute
  '/employer/': typeof EmployerIndexRoute
  '/dashboard_/ats/$id': typeof DashboardAtsIdRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/dashboard_/ats/': typeof DashboardAtsIndexRoute
  '/employer/jobs/$id/applicants': typeof EmployerJobsIdApplicantsRoute
  '/employer/jobs/$id/edit': typeof EmployerJobsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/features'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/reset-password'
    | '/saved'
    | '/settings'
    | '/signup'
    | '/auth/callback'
    | '/dashboard/applications'
    | '/dashboard/resume'
    | '/jobs/$id'
    | '/employer/'
    | '/dashboard/ats/$id'
    | '/employer/jobs/new'
    | '/dashboard/ats/'
    | '/employer/jobs/$id/applicants'
    | '/employer/jobs/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/features'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/reset-password'
    | '/saved'
    | '/settings'
    | '/signup'
    | '/auth/callback'
    | '/dashboard/applications'
    | '/dashboard/resume'
    | '/jobs/$id'
    | '/employer'
    | '/dashboard/ats/$id'
    | '/employer/jobs/new'
    | '/dashboard/ats'
    | '/employer/jobs/$id/applicants'
    | '/employer/jobs/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/features'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/reset-password'
    | '/saved'
    | '/settings'
    | '/signup'
    | '/auth/callback'
    | '/dashboard_/applications'
    | '/dashboard_/resume'
    | '/jobs/$id'
    | '/employer/'
    | '/dashboard_/ats/$id'
    | '/employer/jobs/new'
    | '/dashboard_/ats/'
    | '/employer/jobs/$id/applicants'
    | '/employer/jobs/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  DashboardApplicationsRoute: typeof DashboardApplicationsRoute
  DashboardResumeRoute: typeof DashboardResumeRoute
  EmployerIndexRoute: typeof EmployerIndexRoute
  DashboardAtsIdRoute: typeof DashboardAtsIdRoute
  EmployerJobsNewRoute: typeof EmployerJobsNewRoute
  DashboardAtsIndexRoute: typeof DashboardAtsIndexRoute
  EmployerJobsIdApplicantsRoute: typeof EmployerJobsIdApplicantsRoute
  EmployerJobsIdEditRoute: typeof EmployerJobsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/': {
      id: '/employer/'
      path: '/employer'
      fullPath: '/employer/'
      preLoaderRoute: typeof EmployerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/dashboard_/resume': {
      id: '/dashboard_/resume'
      path: '/dashboard/resume'
      fullPath: '/dashboard/resume'
      preLoaderRoute: typeof DashboardResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/applications': {
      id: '/dashboard_/applications'
      path: '/dashboard/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof DashboardApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard_/ats/': {
      id: '/dashboard_/ats/'
      path: '/dashboard/ats'
      fullPath: '/dashboard/ats/'
      preLoaderRoute: typeof DashboardAtsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/jobs/new': {
      id: '/employer/jobs/new'
      path: '/employer/jobs/new'
      fullPath: '/employer/jobs/new'
      preLoaderRoute: typeof EmployerJobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/ats/$id': {
      id: '/dashboard_/ats/$id'
      path: '/dashboard/ats/$id'
      fullPath: '/dashboard/ats/$id'
      preLoaderRoute: typeof DashboardAtsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/jobs/$id/edit': {
      id: '/employer/jobs/$id/edit'
      path: '/employer/jobs/$id/edit'
      fullPath: '/employer/jobs/$id/edit'
      preLoaderRoute: typeof EmployerJobsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/jobs/$id/applicants': {
      id: '/employer/jobs/$id/applicants'
      path: '/employer/jobs/$id/applicants'
      fullPath: '/employer/jobs/$id/applicants'
      preLoaderRoute: typeof EmployerJobsIdApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface JobsRouteChildren {
  JobsIdRoute: typeof JobsIdRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsIdRoute: JobsIdRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  DashboardApplicationsRoute: DashboardApplicationsRoute,
  DashboardResumeRoute: DashboardResumeRoute,
  EmployerIndexRoute: EmployerIndexRoute,
  DashboardAtsIdRoute: DashboardAtsIdRoute,
  EmployerJobsNewRoute: EmployerJobsNewRoute,
  DashboardAtsIndexRoute: DashboardAtsIndexRoute,
  EmployerJobsIdApplicantsRoute: EmployerJobsIdApplicantsRoute,
  EmployerJobsIdEditRoute: EmployerJobsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
